### ISSUE TITLE
Contests index page is broken

### ISSUE THREAD

**Issue by afedotov** [dmint789/cubing-contests#7]
Hey!
Is there something wrong with current deployment?
Contests index page URL `https://cubingcontests.com/competitions` in any case responds with `HTTP 304`, so contests page is not available unless it is cached by browser previously.

**Comment by dmint789** [comment]
Yeah, I noticed this issue today and just deployed the fix

**Comment by dmint789** [comment]
Nevermind, it's not been fixed still...

**Comment by dmint789** [comment]
Okay, I hope it's fixed now, I'm able to open the contests page. Although last time I also saw it, so I hope it doesn't break again on its own.

**Comment by dmint789** [comment]
Ugh, nevermind, the bug came back after a few hours...

**Comment by dmint789** [comment]
Ok, this has been fixed for good now
